### ISSUE TITLE
win 客户端和其他的客户端怎么用那 麻烦指教

### ISSUE THREAD

**Issue by xrw001** [clangcn/ngrok-one-key-install#1]

**Comment by clangcn** [comment]
http://blog.csdn.net/l631068264/article/details/41990409
请参考

**Comment by clangcn** [comment]
client_ngrok_windows_386.exe -config ngrok.conf start httptun mian

**Comment by clangcn** [comment]
ngrok.conf

```
server_addr: youdomain.com:4443
trust_host_root_certs: false
inspect_addr: disabled
auth_token: test
password: "MjRsYVSA98Ixs1RM"

tunnels:

    httptun:
      remote_port: 8443
      subdomain: "www.test"
      proto:
        https: 192.168.1.1:80
    mian:
        remote_port: 12322
        proto:
            tcp: 192.168.1.1:22
```
