### ISSUE TITLE
求linux_arm客户端和ngrok.cfg客户端配置文件示例

### ISSUE THREAD

**Issue by tangyl2000** [clangcn/ngrok-one-key-install#2]
求大神提供一份linux_arm客户端，另求一份win和linux下客户端所需的ngrok,cfg文件，跪谢了！！！！

**Comment by tangyl2000** [comment]
另外，貌似添加新用户的时候，只能加域名，如何为新用户添加tcp端口转发功能？比如ssh的22端口。求助~~~

**Comment by clangcn** [comment]
./client_ngrok_linux_arm5 -config ngrok.conf start httptun mian

**Comment by clangcn** [comment]
ngrok.conf示例：

```
server_addr: youdomain.com:4443
trust_host_root_certs: false
inspect_addr: disabled
auth_token: test
password: "MjRsYVSA98Ixs1RM"

tunnels:

    httptun:
      remote_port: 8443
      subdomain: "www.test"
      proto:
        https: 192.168.1.1:80
    mian:
        remote_port: 12322
        proto:
            tcp: 192.168.1.1:22

```
