### ISSUE TITLE
能提供下说明文档吗？

### ISSUE THREAD

**Issue by odao** [clangcn/ngrok-one-key-install#3]
您好，这是我的配置内容,链接后一直在重连，服务端就是报remote error: bad certificate错误。请指点一下，谢谢！

```
server_addr: "xxx.xxxx.xxx:4443" #您脚本设置的域名
trust_host_root_certs: false #这个参数无论true,false都无效
auth_token: "xxxxxxxxxxxxxxxx" #您脚本生成的password，这句有没有都无效
tunnels:
  local:
    subdomain: "xxxxx" #针对用户生成的子域名
    auth: "username:password" #addUser设置的用户名和密码
    proto:
      http: 8080 #映射本地端口号

```

**Comment by odao** [comment]
请问有mac版的客户端吗？

**Comment by clangcn** [comment]
```
server_addr: youdomain.com:4443
trust_host_root_certs: false
inspect_addr: disabled
auth_token: test
password: "MjRsYVSA98Ixs1RM"

tunnels:

    httptun:
      remote_port: 8443
      subdomain: "www.test"
      proto:
        https: 192.168.1.1:80
    mian:
        remote_port: 12322
        proto:
            tcp: 192.168.1.1:22
```
